/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteImport } from './routes/_platform'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PlatformIndexRouteImport } from './routes/_platform/index'
import { Route as FIdRouteImport } from './routes/f.$id'
import { Route as PlatformRedirectRouteImport } from './routes/_platform/redirect'
import { Route as PlatformWebhooksIndexRouteImport } from './routes/_platform/webhooks.index'
import { Route as PlatformTagsIndexRouteImport } from './routes/_platform/tags.index'
import { Route as PlatformFormsIndexRouteImport } from './routes/_platform/forms.index'
import { Route as FormsIdPreviewRouteImport } from './routes/forms.$id.preview'
import { Route as PlatformWebhooksNewRouteImport } from './routes/_platform/webhooks.new'
import { Route as PlatformFormsIdRouteImport } from './routes/_platform/forms.$id'
import { Route as AuthSignUpSplatRouteImport } from './routes/_auth/sign-up.$'
import { Route as AuthSignInSplatRouteImport } from './routes/_auth/sign-in.$'
import { Route as PlatformWebhooksIdIndexRouteImport } from './routes/_platform/webhooks.$id.index'
import { Route as PlatformFormsIdIndexRouteImport } from './routes/_platform/forms.$id.index'
import { Route as PlatformFormsIdTimelineRouteImport } from './routes/_platform/forms.$id.timeline'
import { Route as PlatformFormsIdSubmissionsRouteImport } from './routes/_platform/forms.$id.submissions'
import { Route as PlatformFormsIdSettingsRouteImport } from './routes/_platform/forms.$id.settings'
import { Route as PlatformFormsIdAnalyticsRouteImport } from './routes/_platform/forms.$id.analytics'

const PlatformRoute = PlatformRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const FIdRoute = FIdRouteImport.update({
  id: '/f/$id',
  path: '/f/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRedirectRoute = PlatformRedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformWebhooksIndexRoute = PlatformWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformTagsIndexRoute = PlatformTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformFormsIndexRoute = PlatformFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => PlatformRoute,
} as any)
const FormsIdPreviewRoute = FormsIdPreviewRouteImport.update({
  id: '/forms/$id/preview',
  path: '/forms/$id/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformWebhooksNewRoute = PlatformWebhooksNewRouteImport.update({
  id: '/webhooks/new',
  path: '/webhooks/new',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformFormsIdRoute = PlatformFormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => PlatformRoute,
} as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInSplatRoute = AuthSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => AuthRoute,
} as any)
const PlatformWebhooksIdIndexRoute = PlatformWebhooksIdIndexRouteImport.update({
  id: '/webhooks/$id/',
  path: '/webhooks/$id/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformFormsIdIndexRoute = PlatformFormsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformFormsIdRoute,
} as any)
const PlatformFormsIdTimelineRoute = PlatformFormsIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => PlatformFormsIdRoute,
} as any)
const PlatformFormsIdSubmissionsRoute =
  PlatformFormsIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => PlatformFormsIdRoute,
  } as any)
const PlatformFormsIdSettingsRoute = PlatformFormsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlatformFormsIdRoute,
} as any)
const PlatformFormsIdAnalyticsRoute =
  PlatformFormsIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => PlatformFormsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/redirect': typeof PlatformRedirectRoute
  '/f/$id': typeof FIdRoute
  '/': typeof PlatformIndexRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/forms/$id': typeof PlatformFormsIdRouteWithChildren
  '/webhooks/new': typeof PlatformWebhooksNewRoute
  '/forms/$id/preview': typeof FormsIdPreviewRoute
  '/forms': typeof PlatformFormsIndexRoute
  '/tags': typeof PlatformTagsIndexRoute
  '/webhooks': typeof PlatformWebhooksIndexRoute
  '/forms/$id/analytics': typeof PlatformFormsIdAnalyticsRoute
  '/forms/$id/settings': typeof PlatformFormsIdSettingsRoute
  '/forms/$id/submissions': typeof PlatformFormsIdSubmissionsRoute
  '/forms/$id/timeline': typeof PlatformFormsIdTimelineRoute
  '/forms/$id/': typeof PlatformFormsIdIndexRoute
  '/webhooks/$id': typeof PlatformWebhooksIdIndexRoute
}
export interface FileRoutesByTo {
  '/redirect': typeof PlatformRedirectRoute
  '/f/$id': typeof FIdRoute
  '/': typeof PlatformIndexRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/webhooks/new': typeof PlatformWebhooksNewRoute
  '/forms/$id/preview': typeof FormsIdPreviewRoute
  '/forms': typeof PlatformFormsIndexRoute
  '/tags': typeof PlatformTagsIndexRoute
  '/webhooks': typeof PlatformWebhooksIndexRoute
  '/forms/$id/analytics': typeof PlatformFormsIdAnalyticsRoute
  '/forms/$id/settings': typeof PlatformFormsIdSettingsRoute
  '/forms/$id/submissions': typeof PlatformFormsIdSubmissionsRoute
  '/forms/$id/timeline': typeof PlatformFormsIdTimelineRoute
  '/forms/$id': typeof PlatformFormsIdIndexRoute
  '/webhooks/$id': typeof PlatformWebhooksIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_platform': typeof PlatformRouteWithChildren
  '/_platform/redirect': typeof PlatformRedirectRoute
  '/f/$id': typeof FIdRoute
  '/_platform/': typeof PlatformIndexRoute
  '/_auth/sign-in/$': typeof AuthSignInSplatRoute
  '/_auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/_platform/forms/$id': typeof PlatformFormsIdRouteWithChildren
  '/_platform/webhooks/new': typeof PlatformWebhooksNewRoute
  '/forms/$id/preview': typeof FormsIdPreviewRoute
  '/_platform/forms/': typeof PlatformFormsIndexRoute
  '/_platform/tags/': typeof PlatformTagsIndexRoute
  '/_platform/webhooks/': typeof PlatformWebhooksIndexRoute
  '/_platform/forms/$id/analytics': typeof PlatformFormsIdAnalyticsRoute
  '/_platform/forms/$id/settings': typeof PlatformFormsIdSettingsRoute
  '/_platform/forms/$id/submissions': typeof PlatformFormsIdSubmissionsRoute
  '/_platform/forms/$id/timeline': typeof PlatformFormsIdTimelineRoute
  '/_platform/forms/$id/': typeof PlatformFormsIdIndexRoute
  '/_platform/webhooks/$id/': typeof PlatformWebhooksIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/redirect'
    | '/f/$id'
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/forms/$id'
    | '/webhooks/new'
    | '/forms/$id/preview'
    | '/forms'
    | '/tags'
    | '/webhooks'
    | '/forms/$id/analytics'
    | '/forms/$id/settings'
    | '/forms/$id/submissions'
    | '/forms/$id/timeline'
    | '/forms/$id/'
    | '/webhooks/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/redirect'
    | '/f/$id'
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/webhooks/new'
    | '/forms/$id/preview'
    | '/forms'
    | '/tags'
    | '/webhooks'
    | '/forms/$id/analytics'
    | '/forms/$id/settings'
    | '/forms/$id/submissions'
    | '/forms/$id/timeline'
    | '/forms/$id'
    | '/webhooks/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_platform'
    | '/_platform/redirect'
    | '/f/$id'
    | '/_platform/'
    | '/_auth/sign-in/$'
    | '/_auth/sign-up/$'
    | '/_platform/forms/$id'
    | '/_platform/webhooks/new'
    | '/forms/$id/preview'
    | '/_platform/forms/'
    | '/_platform/tags/'
    | '/_platform/webhooks/'
    | '/_platform/forms/$id/analytics'
    | '/_platform/forms/$id/settings'
    | '/_platform/forms/$id/submissions'
    | '/_platform/forms/$id/timeline'
    | '/_platform/forms/$id/'
    | '/_platform/webhooks/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
  FIdRoute: typeof FIdRoute
  FormsIdPreviewRoute: typeof FormsIdPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/': {
      id: '/_platform/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/f/$id': {
      id: '/f/$id'
      path: '/f/$id'
      fullPath: '/f/$id'
      preLoaderRoute: typeof FIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/redirect': {
      id: '/_platform/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof PlatformRedirectRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/webhooks/': {
      id: '/_platform/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof PlatformWebhooksIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/tags/': {
      id: '/_platform/tags/'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof PlatformTagsIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/forms/': {
      id: '/_platform/forms/'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof PlatformFormsIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/forms/$id/preview': {
      id: '/forms/$id/preview'
      path: '/forms/$id/preview'
      fullPath: '/forms/$id/preview'
      preLoaderRoute: typeof FormsIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/webhooks/new': {
      id: '/_platform/webhooks/new'
      path: '/webhooks/new'
      fullPath: '/webhooks/new'
      preLoaderRoute: typeof PlatformWebhooksNewRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/forms/$id': {
      id: '/_platform/forms/$id'
      path: '/forms/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof PlatformFormsIdRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_auth/sign-up/$': {
      id: '/_auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in/$': {
      id: '/_auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AuthSignInSplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_platform/webhooks/$id/': {
      id: '/_platform/webhooks/$id/'
      path: '/webhooks/$id'
      fullPath: '/webhooks/$id'
      preLoaderRoute: typeof PlatformWebhooksIdIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/forms/$id/': {
      id: '/_platform/forms/$id/'
      path: '/'
      fullPath: '/forms/$id/'
      preLoaderRoute: typeof PlatformFormsIdIndexRouteImport
      parentRoute: typeof PlatformFormsIdRoute
    }
    '/_platform/forms/$id/timeline': {
      id: '/_platform/forms/$id/timeline'
      path: '/timeline'
      fullPath: '/forms/$id/timeline'
      preLoaderRoute: typeof PlatformFormsIdTimelineRouteImport
      parentRoute: typeof PlatformFormsIdRoute
    }
    '/_platform/forms/$id/submissions': {
      id: '/_platform/forms/$id/submissions'
      path: '/submissions'
      fullPath: '/forms/$id/submissions'
      preLoaderRoute: typeof PlatformFormsIdSubmissionsRouteImport
      parentRoute: typeof PlatformFormsIdRoute
    }
    '/_platform/forms/$id/settings': {
      id: '/_platform/forms/$id/settings'
      path: '/settings'
      fullPath: '/forms/$id/settings'
      preLoaderRoute: typeof PlatformFormsIdSettingsRouteImport
      parentRoute: typeof PlatformFormsIdRoute
    }
    '/_platform/forms/$id/analytics': {
      id: '/_platform/forms/$id/analytics'
      path: '/analytics'
      fullPath: '/forms/$id/analytics'
      preLoaderRoute: typeof PlatformFormsIdAnalyticsRouteImport
      parentRoute: typeof PlatformFormsIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInSplatRoute: AuthSignInSplatRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PlatformFormsIdRouteChildren {
  PlatformFormsIdAnalyticsRoute: typeof PlatformFormsIdAnalyticsRoute
  PlatformFormsIdSettingsRoute: typeof PlatformFormsIdSettingsRoute
  PlatformFormsIdSubmissionsRoute: typeof PlatformFormsIdSubmissionsRoute
  PlatformFormsIdTimelineRoute: typeof PlatformFormsIdTimelineRoute
  PlatformFormsIdIndexRoute: typeof PlatformFormsIdIndexRoute
}

const PlatformFormsIdRouteChildren: PlatformFormsIdRouteChildren = {
  PlatformFormsIdAnalyticsRoute: PlatformFormsIdAnalyticsRoute,
  PlatformFormsIdSettingsRoute: PlatformFormsIdSettingsRoute,
  PlatformFormsIdSubmissionsRoute: PlatformFormsIdSubmissionsRoute,
  PlatformFormsIdTimelineRoute: PlatformFormsIdTimelineRoute,
  PlatformFormsIdIndexRoute: PlatformFormsIdIndexRoute,
}

const PlatformFormsIdRouteWithChildren = PlatformFormsIdRoute._addFileChildren(
  PlatformFormsIdRouteChildren,
)

interface PlatformRouteChildren {
  PlatformRedirectRoute: typeof PlatformRedirectRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformFormsIdRoute: typeof PlatformFormsIdRouteWithChildren
  PlatformWebhooksNewRoute: typeof PlatformWebhooksNewRoute
  PlatformFormsIndexRoute: typeof PlatformFormsIndexRoute
  PlatformTagsIndexRoute: typeof PlatformTagsIndexRoute
  PlatformWebhooksIndexRoute: typeof PlatformWebhooksIndexRoute
  PlatformWebhooksIdIndexRoute: typeof PlatformWebhooksIdIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformRedirectRoute: PlatformRedirectRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformFormsIdRoute: PlatformFormsIdRouteWithChildren,
  PlatformWebhooksNewRoute: PlatformWebhooksNewRoute,
  PlatformFormsIndexRoute: PlatformFormsIndexRoute,
  PlatformTagsIndexRoute: PlatformTagsIndexRoute,
  PlatformWebhooksIndexRoute: PlatformWebhooksIndexRoute,
  PlatformWebhooksIdIndexRoute: PlatformWebhooksIdIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
  FIdRoute: FIdRoute,
  FormsIdPreviewRoute: FormsIdPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
