/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteImport } from './routes/_platform'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PlatformChar123SlugChar125RouteImport } from './routes/_platform/{-$slug}'
import { Route as PlatformRedirectRouteImport } from './routes/_platform/redirect'
import { Route as PlatformChar123SlugChar125IndexRouteImport } from './routes/_platform/{-$slug}/index'
import { Route as AuthSignUpSplatRouteImport } from './routes/_auth/sign-up.$'
import { Route as AuthSignInSplatRouteImport } from './routes/_auth/sign-in.$'
import { Route as PlatformChar123SlugChar125FormsIndexRouteImport } from './routes/_platform/{-$slug}/forms.index'
import { Route as PlatformChar123SlugChar125FormsIdRouteImport } from './routes/_platform/{-$slug}/forms.$id'
import { Route as PlatformChar123SlugChar125FormsIdIndexRouteImport } from './routes/_platform/{-$slug}/forms.$id.index'
import { Route as PlatformChar123SlugChar125FormsIdTimelineRouteImport } from './routes/_platform/{-$slug}/forms.$id.timeline'
import { Route as PlatformChar123SlugChar125FormsIdSubmissionsRouteImport } from './routes/_platform/{-$slug}/forms.$id.submissions'
import { Route as PlatformChar123SlugChar125FormsIdSettingsRouteImport } from './routes/_platform/{-$slug}/forms.$id.settings'

const PlatformRoute = PlatformRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformChar123SlugChar125Route =
  PlatformChar123SlugChar125RouteImport.update({
    id: '/{-$slug}',
    path: '/{-$slug}',
    getParentRoute: () => PlatformRoute,
  } as any)
const PlatformRedirectRoute = PlatformRedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformChar123SlugChar125IndexRoute =
  PlatformChar123SlugChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PlatformChar123SlugChar125Route,
  } as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInSplatRoute = AuthSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => AuthRoute,
} as any)
const PlatformChar123SlugChar125FormsIndexRoute =
  PlatformChar123SlugChar125FormsIndexRouteImport.update({
    id: '/forms/',
    path: '/forms/',
    getParentRoute: () => PlatformChar123SlugChar125Route,
  } as any)
const PlatformChar123SlugChar125FormsIdRoute =
  PlatformChar123SlugChar125FormsIdRouteImport.update({
    id: '/forms/$id',
    path: '/forms/$id',
    getParentRoute: () => PlatformChar123SlugChar125Route,
  } as any)
const PlatformChar123SlugChar125FormsIdIndexRoute =
  PlatformChar123SlugChar125FormsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PlatformChar123SlugChar125FormsIdRoute,
  } as any)
const PlatformChar123SlugChar125FormsIdTimelineRoute =
  PlatformChar123SlugChar125FormsIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => PlatformChar123SlugChar125FormsIdRoute,
  } as any)
const PlatformChar123SlugChar125FormsIdSubmissionsRoute =
  PlatformChar123SlugChar125FormsIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => PlatformChar123SlugChar125FormsIdRoute,
  } as any)
const PlatformChar123SlugChar125FormsIdSettingsRoute =
  PlatformChar123SlugChar125FormsIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => PlatformChar123SlugChar125FormsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/redirect': typeof PlatformRedirectRoute
  '/{-$slug}': typeof PlatformChar123SlugChar125RouteWithChildren
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/{-$slug}/': typeof PlatformChar123SlugChar125IndexRoute
  '/{-$slug}/forms/$id': typeof PlatformChar123SlugChar125FormsIdRouteWithChildren
  '/{-$slug}/forms': typeof PlatformChar123SlugChar125FormsIndexRoute
  '/{-$slug}/forms/$id/settings': typeof PlatformChar123SlugChar125FormsIdSettingsRoute
  '/{-$slug}/forms/$id/submissions': typeof PlatformChar123SlugChar125FormsIdSubmissionsRoute
  '/{-$slug}/forms/$id/timeline': typeof PlatformChar123SlugChar125FormsIdTimelineRoute
  '/{-$slug}/forms/$id/': typeof PlatformChar123SlugChar125FormsIdIndexRoute
}
export interface FileRoutesByTo {
  '/redirect': typeof PlatformRedirectRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/{-$slug}': typeof PlatformChar123SlugChar125IndexRoute
  '/{-$slug}/forms': typeof PlatformChar123SlugChar125FormsIndexRoute
  '/{-$slug}/forms/$id/settings': typeof PlatformChar123SlugChar125FormsIdSettingsRoute
  '/{-$slug}/forms/$id/submissions': typeof PlatformChar123SlugChar125FormsIdSubmissionsRoute
  '/{-$slug}/forms/$id/timeline': typeof PlatformChar123SlugChar125FormsIdTimelineRoute
  '/{-$slug}/forms/$id': typeof PlatformChar123SlugChar125FormsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_platform': typeof PlatformRouteWithChildren
  '/_platform/redirect': typeof PlatformRedirectRoute
  '/_platform/{-$slug}': typeof PlatformChar123SlugChar125RouteWithChildren
  '/_auth/sign-in/$': typeof AuthSignInSplatRoute
  '/_auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/_platform/{-$slug}/': typeof PlatformChar123SlugChar125IndexRoute
  '/_platform/{-$slug}/forms/$id': typeof PlatformChar123SlugChar125FormsIdRouteWithChildren
  '/_platform/{-$slug}/forms/': typeof PlatformChar123SlugChar125FormsIndexRoute
  '/_platform/{-$slug}/forms/$id/settings': typeof PlatformChar123SlugChar125FormsIdSettingsRoute
  '/_platform/{-$slug}/forms/$id/submissions': typeof PlatformChar123SlugChar125FormsIdSubmissionsRoute
  '/_platform/{-$slug}/forms/$id/timeline': typeof PlatformChar123SlugChar125FormsIdTimelineRoute
  '/_platform/{-$slug}/forms/$id/': typeof PlatformChar123SlugChar125FormsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/redirect'
    | '/{-$slug}'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/{-$slug}/'
    | '/{-$slug}/forms/$id'
    | '/{-$slug}/forms'
    | '/{-$slug}/forms/$id/settings'
    | '/{-$slug}/forms/$id/submissions'
    | '/{-$slug}/forms/$id/timeline'
    | '/{-$slug}/forms/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/redirect'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/{-$slug}'
    | '/{-$slug}/forms'
    | '/{-$slug}/forms/$id/settings'
    | '/{-$slug}/forms/$id/submissions'
    | '/{-$slug}/forms/$id/timeline'
    | '/{-$slug}/forms/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_platform'
    | '/_platform/redirect'
    | '/_platform/{-$slug}'
    | '/_auth/sign-in/$'
    | '/_auth/sign-up/$'
    | '/_platform/{-$slug}/'
    | '/_platform/{-$slug}/forms/$id'
    | '/_platform/{-$slug}/forms/'
    | '/_platform/{-$slug}/forms/$id/settings'
    | '/_platform/{-$slug}/forms/$id/submissions'
    | '/_platform/{-$slug}/forms/$id/timeline'
    | '/_platform/{-$slug}/forms/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/{-$slug}': {
      id: '/_platform/{-$slug}'
      path: '/{-$slug}'
      fullPath: '/{-$slug}'
      preLoaderRoute: typeof PlatformChar123SlugChar125RouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/redirect': {
      id: '/_platform/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof PlatformRedirectRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/{-$slug}/': {
      id: '/_platform/{-$slug}/'
      path: '/'
      fullPath: '/{-$slug}/'
      preLoaderRoute: typeof PlatformChar123SlugChar125IndexRouteImport
      parentRoute: typeof PlatformChar123SlugChar125Route
    }
    '/_auth/sign-up/$': {
      id: '/_auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in/$': {
      id: '/_auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AuthSignInSplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_platform/{-$slug}/forms/': {
      id: '/_platform/{-$slug}/forms/'
      path: '/forms'
      fullPath: '/{-$slug}/forms'
      preLoaderRoute: typeof PlatformChar123SlugChar125FormsIndexRouteImport
      parentRoute: typeof PlatformChar123SlugChar125Route
    }
    '/_platform/{-$slug}/forms/$id': {
      id: '/_platform/{-$slug}/forms/$id'
      path: '/forms/$id'
      fullPath: '/{-$slug}/forms/$id'
      preLoaderRoute: typeof PlatformChar123SlugChar125FormsIdRouteImport
      parentRoute: typeof PlatformChar123SlugChar125Route
    }
    '/_platform/{-$slug}/forms/$id/': {
      id: '/_platform/{-$slug}/forms/$id/'
      path: '/'
      fullPath: '/{-$slug}/forms/$id/'
      preLoaderRoute: typeof PlatformChar123SlugChar125FormsIdIndexRouteImport
      parentRoute: typeof PlatformChar123SlugChar125FormsIdRoute
    }
    '/_platform/{-$slug}/forms/$id/timeline': {
      id: '/_platform/{-$slug}/forms/$id/timeline'
      path: '/timeline'
      fullPath: '/{-$slug}/forms/$id/timeline'
      preLoaderRoute: typeof PlatformChar123SlugChar125FormsIdTimelineRouteImport
      parentRoute: typeof PlatformChar123SlugChar125FormsIdRoute
    }
    '/_platform/{-$slug}/forms/$id/submissions': {
      id: '/_platform/{-$slug}/forms/$id/submissions'
      path: '/submissions'
      fullPath: '/{-$slug}/forms/$id/submissions'
      preLoaderRoute: typeof PlatformChar123SlugChar125FormsIdSubmissionsRouteImport
      parentRoute: typeof PlatformChar123SlugChar125FormsIdRoute
    }
    '/_platform/{-$slug}/forms/$id/settings': {
      id: '/_platform/{-$slug}/forms/$id/settings'
      path: '/settings'
      fullPath: '/{-$slug}/forms/$id/settings'
      preLoaderRoute: typeof PlatformChar123SlugChar125FormsIdSettingsRouteImport
      parentRoute: typeof PlatformChar123SlugChar125FormsIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInSplatRoute: AuthSignInSplatRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PlatformChar123SlugChar125FormsIdRouteChildren {
  PlatformChar123SlugChar125FormsIdSettingsRoute: typeof PlatformChar123SlugChar125FormsIdSettingsRoute
  PlatformChar123SlugChar125FormsIdSubmissionsRoute: typeof PlatformChar123SlugChar125FormsIdSubmissionsRoute
  PlatformChar123SlugChar125FormsIdTimelineRoute: typeof PlatformChar123SlugChar125FormsIdTimelineRoute
  PlatformChar123SlugChar125FormsIdIndexRoute: typeof PlatformChar123SlugChar125FormsIdIndexRoute
}

const PlatformChar123SlugChar125FormsIdRouteChildren: PlatformChar123SlugChar125FormsIdRouteChildren =
  {
    PlatformChar123SlugChar125FormsIdSettingsRoute:
      PlatformChar123SlugChar125FormsIdSettingsRoute,
    PlatformChar123SlugChar125FormsIdSubmissionsRoute:
      PlatformChar123SlugChar125FormsIdSubmissionsRoute,
    PlatformChar123SlugChar125FormsIdTimelineRoute:
      PlatformChar123SlugChar125FormsIdTimelineRoute,
    PlatformChar123SlugChar125FormsIdIndexRoute:
      PlatformChar123SlugChar125FormsIdIndexRoute,
  }

const PlatformChar123SlugChar125FormsIdRouteWithChildren =
  PlatformChar123SlugChar125FormsIdRoute._addFileChildren(
    PlatformChar123SlugChar125FormsIdRouteChildren,
  )

interface PlatformChar123SlugChar125RouteChildren {
  PlatformChar123SlugChar125IndexRoute: typeof PlatformChar123SlugChar125IndexRoute
  PlatformChar123SlugChar125FormsIdRoute: typeof PlatformChar123SlugChar125FormsIdRouteWithChildren
  PlatformChar123SlugChar125FormsIndexRoute: typeof PlatformChar123SlugChar125FormsIndexRoute
}

const PlatformChar123SlugChar125RouteChildren: PlatformChar123SlugChar125RouteChildren =
  {
    PlatformChar123SlugChar125IndexRoute: PlatformChar123SlugChar125IndexRoute,
    PlatformChar123SlugChar125FormsIdRoute:
      PlatformChar123SlugChar125FormsIdRouteWithChildren,
    PlatformChar123SlugChar125FormsIndexRoute:
      PlatformChar123SlugChar125FormsIndexRoute,
  }

const PlatformChar123SlugChar125RouteWithChildren =
  PlatformChar123SlugChar125Route._addFileChildren(
    PlatformChar123SlugChar125RouteChildren,
  )

interface PlatformRouteChildren {
  PlatformRedirectRoute: typeof PlatformRedirectRoute
  PlatformChar123SlugChar125Route: typeof PlatformChar123SlugChar125RouteWithChildren
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformRedirectRoute: PlatformRedirectRoute,
  PlatformChar123SlugChar125Route: PlatformChar123SlugChar125RouteWithChildren,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
